### ISSUE TITLE
Price Oracle Issue

### ISSUE THREAD

**Issue by PatrickCroke** [keyko-io/defi-crawler-py#36]
when invoking the get_price_at_timestamp method for chainlink oracle, I received this error: 
![Screen Shot 2021-06-08 at 12 30 52 PM](https://user-images.githubusercontent.com/50606705/121223339-6b208200-c855-11eb-8d00-4aeb771a3408.png)

May need to alter parentheses around len(prices) instead of len(prices > 0)

**Comment by ialberquilla** [comment]
Thanks @PatrickCroke 

Yes, was an error on the parenthesis, change here https://github.com/keyko-io/defi-crawler-py/pull/38
