### ISSUE TITLE
Code returns "ValueError: Invalid String"

### ISSUE THREAD

**Issue by sekohen** [keyko-io/defi-crawler-py#41]
`# Instanciate the oracle with the name, version and chain`
`from deficrawler import Oracle`
`from datetime import datetime`

`chainlink = Oracle(protocol="chainlink", version=1, chain="Ethereum")`
`data=chainlink.get_price_from_date_range(from_date="01/07/2021 00:00:00", to_date="05/07/2021 00:00:00", pair="ETH/USDT")`
`print(data)`

The above code returns the following:

...oracle.py", line 41, in get_price_from_date_range
datetime.strptime(from_date, '%d/%m/%Y %H:%M:%S').strftime("%s"))
ValueError: Invalid format string

**Comment by evanwimpey** [comment]
I had same issue. Pull request #42 should resolve

**Comment by ialberquilla** [comment]
Hey @sekohen @evanwimpey  Thanks for your comments and PR! Will check this issue and merge the PR to solve. Let you know

**Comment by ialberquilla** [comment]
PR is now merge and all the timestamps format changed. Can you test it now?
