### ISSUE TITLE
Identify FlashLoan from UniSwap (as FlashSwap)

### ISSUE THREAD

**Issue by fpietrosanti** [keyko-io/defi-crawler-py#69]
Defi-Crawler does not seems to identify flashloan uses from FlashSwap.

I was looking at this paper only focusing on Aave, because defi-crawler support only this:
https://python.plainenglish.io/flashloan-stats-on-aave-for-2021-e827dd232052

From the paper that extended to UniSwap:
Towards A First Step to Understand Flash Loan and Its Applications in DeFi Ecosystem https://arxiv.org/pdf/2010.12252.pdf

<img width="343" alt="Screenshot 2021-12-27 at 23 28 08" src="https://user-images.githubusercontent.com/770363/147511130-bf7e354a-a368-47f0-b7af-64fe5d7c9067.png">

**Comment by ialberquilla** [comment]
This library has access to all the swaps done on uniswap. Flash swaps are just a swap with a callback where other transactions happen, so it's not easy to differentiate from a normal swap. You can group the swaps with the same tx id and sender to find swaps in the same block, that are potentially flash swaps.
