### ISSUE TITLE
Compound endpoint not working

### ISSUE THREAD

**Issue by gerrit593** [keyko-io/defi-crawler-py#76]
Hi!

Last week I went through the examples provided here on Github, everything worked perfectly.

Today, the Compound endpoint seems not to work anymore:

`
Exception:` There was an error getting the data from TheGraph{"errors": [{"message": "deployment `graphprotocol/compound-v2` does not exist", "locations": [{"line": 2, "column": 17}], "path": ["borrowEvents"], "extensions": {"code": "INTERNAL_SERVER_ERROR", "exception": {"errors": [{"message": "deployment `graphprotocol/compound-v2` does not exist", "locations": [], "path": ["borrowEvents"]}]}}}], "data": null}
`
I use version 0.4.0.

**Comment by ialberquilla** [comment]
Hi,

Looks like the compound subgraph is not deployed anymore https://thegraph.com/hosted-service/subgraph/graphprotocol/compound-v2

Will try to find an alternative.

**Comment by gerrit593** [comment]
It is working again. Seemed to be a temporary issue.
Thanks!
